// CONST FOR ADD CLASSES

export const CLASSES_SUCCESS = "CLASSES_SUCCESS";
export const CLASSES_PENDING = "CLASSES_PENDING";
export const CLASSES_FAILED = "CLASSES_FAILED";

// const for fetch class data
export const FETCH_CLASS_SUCCESS = "FETCH_CLASS_SUCCES";
export const FETCH_CLASS_PENDING = "FETCH_CLASS_PENDING";
export const FETCH_CLASS_FAILED = "FETCH_CLASS_FAILED";

// CONST FOR STUDENTS
