// CONST FOR ADD CLASSES

export const CLASSES_SUCCESS = "CLASSES_SUCCESS";
export const CLASSES_PENDING = "CLASSES_PENDING";
export const CLASSES_FAILED = "CLASSES_FAILED";

// const for fetch class data
export const FETCH_CLASS_SUCCESS = "FETCH_CLASS_SUCCES";
export const FETCH_CLASS_PENDING = "FETCH_CLASS_PENDING";
export const FETCH_CLASS_FAILED = "FETCH_CLASS_FAILED";

// CONST FOR STUDENTS

export const STUDENTS_SECCESS = "STUDENTS_SECCESS";
export const STUDENTS_PENDING = "STUDENTS_PENDING";
export const STUDENTS_ERR = "STUDENTS_ERR";

// const fetch for students

const FETCH_STUDENT_SUCCESS = "FETCH_STUDENT_SUCCESS";
const FETCH_STUDENT_PENDING = "FETCH_STUDENT_PENDING";
const FETCH_STUDENT_ERR = "FETCH_STUDENT_ERR";

export { FETCH_STUDENT_ERR, FETCH_STUDENT_PENDING, FETCH_STUDENT_SUCCESS };
